language: go

go:
- 1.13.x

env:
  global:
  - GO111MODULE=on
  - GOPRIVATE=github.com/RTradeLtd/*

  install:
- go mod download

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...

script:
- go test -race -short -coverprofile=coverage.txt ./...

before_deploy:
  - make release-cli

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ghX/jhxQUYP9lBBj07En1I0RhIsOxB3ImwGqE76PP1nVHTmPRJEhtWm3AhF83a33RlSaWDJfD9Kv++PqFcPaMqlv53vj8Yo45AUfEfUfQHvkzNOzuafg7FZWgc9M8jZIUaeIoN6i2Rluoqmlkbk+vjV/KE8GZkUM3WyBkWeMJKVzMc70QcZb0A0jY0IvIGp44K1UjifZwnTsmaoGS4CoNmkt+h3Ys/8IZGjmb4S+/LLe6BJJBkkw02NGw2zDmysizdxHwqbfXVQL0+G6zyUdqA/uSDK0MYTVNzXUJMiCoGaW37k79jjkjLRsXxqhIwVhUu2r/LKer8oZ29F3yKPO/nfBODCFl9iCYJo+pGtt//qLc6CdPocWXal25D7ZBGe/yyLoKUwPEv1duYofOOKuXcI8O9j12JrCF8Q0nccgnVJC7dEQrOlJRnsfJSJz5d85nfzBBSK92dDTJ/xgF/Gemk3RFT1hU+UijE2+pRTvFD4RC0McT5nK3RPpOH+9Oh9j91T5R/Z2OzuPrg1j+a2CFggU9opTFs2LwcT5vIGStI9sREZjTDPVRyURVLjR7l9wxwTAu/Wf3/W9Ot2ObBQKQ0zkxvDR73w5tob/JGzK+AMo2brzFSi1SYJ1oHGpdc1yzPD9xZygeH7Rph/b1VZNAsC3qB4g4r2Co8tbODz/Ymo=
  file_glob: true
  file: release/tex-*
  on:
    tags: true
    repo: RTradeLtd/go-temporalx-sdk

cache:
  directories:
  - "$GOPATH/pkg/mod"
  - "$HOME/.cache/go-build"